name: macOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      # Cloning Repo
      - name: Checkout the repository
        uses: actions/checkout@v3
      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
      # Install Poetry and Allure
      - name: Install Poetry and Allure
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create false
          poetry install
          brew install allure

      # Download previous Allure report history from gh-pages
      - name: Download Allure History
        run: |
          git fetch origin gh-pages
          git checkout gh-pages -- allure-report/history || echo "No previous history found"
        continue-on-error: true
      # Run Tests
      - name: Run tests with pytest
        run: |
          poetry run pytest
        continue-on-error: true
      # Copy Allure History to allure-results
      - name: Copy Allure History
        if: always()
        run: |
          mkdir -p allure-results/history
          cp -r allure-report/history allure-results/ || echo "No history to copy"

      # Generate Allure HTML Report with history
      - name: Generate Allure HTML Report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-report

      # Upload Allure report as GitHub Artifact
      - name: Upload Allure Report
        uses: actions/upload-artifact@v3
        with:
          name: allure-results
          path: allure-results
      # Deploy Allure Report to GitHub Pages
      - name: Deploy Allure Report to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}