name: macOS CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      # Cloning Repo
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      # Install Poetry and Allure
      - name: Install Poetry and Allure
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry config virtualenvs.create false
          poetry install
          brew install allure

      # Download previous Allure report history from gh-pages
      - name: Download Allure History
        run: |
          git fetch origin gh-pages
          git checkout gh-pages -- allure-report/history || echo "No previous history found"
        continue-on-error: true

      # Run Tests
      - name: Run tests with pytest
        run: |
          poetry run pytest
        continue-on-error: true

      # Generate Allure Report with History
      - name: Allure Report with History
        uses: mgrybyk/allure-report-branch-js-action@v1
        with:
          report_id: 'self-test'
          gh_pages: 'gh-pages-dir'
          report_dir: 'allure-results'

      # Push the Allure Report to GitHub Pages
      - name: Git Commit and Push
        uses: mgrybyk/git-commit-pull-push-action@v1
        with:
          repository: gh-pages-dir
          branch: gh-pages
          pull_args: --rebase -X ours